version: '3'
services:
  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo  # Corrected the environment variable name
      MONGO_INITDB_ROOT_USERNAME: abi
      MONGO_INITDB_ROOT_PASSWORD: abi
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  # Express.js server service
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file: .env
    networks:
      - app-network
    depends_on:
      - mongo
    # Remove the "links" section, it's not needed

  # React.js client service
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "3001:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:

