version: '3'
services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db     

  # Express.js server service
  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network    
    depends_on:
      - mongodb

  # React.js client service
  client:
    build: ./client
    depends_on:
      - server    
    ports:
      - "3000:3000"
    networks:
      - app-network

        

networks:
    app-network:
        driver: bridge
volumes:
    data-volume:

